### ISSUE TITLE
Dateformat constraints not explicitly given

### ISSUE THREAD

**Issue by MaheshAravindV** [StephaneBour/actions-calver#23]
**Description**
The action sorts the tags by v:refname to figure out the latest tag which might not be the same ordering as per the calver version. 
The action allows you to specify the date_format and for some date_formats, the sorting by v:refname and calver will not be the same.

**Example scenario**
If the provided date format is dd-mm-yyyy,  (%d-%m-%Y)
git tag --sort=v:refname output
01-02-2024
02-01-2024

this would lead to the action considering the latest version as 02-01-2024. If another release is created on 01-02-2024, it would not realise that a minor version has to be created on that date.

**Expected change**
The docs for the input date_format have to specify this constraint or the tags should be sorted based on created time instead of v:refname

**Comment by MaheshAravindV** [comment]
I can also raise a PR with the fix if I can pick the issue up

**Comment by miigotu** [comment]
That format doesn't really work for calver type versioning. The numbers need to be actually incremental. Otherwise, your versions say if you had 1.2.2023 and 1.3.2020 every package manager out there is going to consider the 2020 version newer than the 2023 version. 2023.1.2 and 2020.1.3 will always process correctly, yyyy.m.d or y.m.d  (no leading zeros) is the basic calver date format, or it can be yyyy.version or yyyy.m.patchlevel, but the major has to be the largest period of time for all the parts you use, and the minor the next largest possible period of time, etc.

**Comment by MaheshAravindV** [comment]
OK. I thought CalVer did not have constraints on the date format to follow. Thank you
